### ISSUE TITLE
RangeError Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AFKLord** [AltimitSystems/mv-plugins#35]
I'm getting the error "RangeError Maximum call stack size exceeded" on only one specific map in RPG Maker MV, the plugin works fine on all other maps. I've disabled all other plugins, however the issue persists on this one map. Most maps are 256x256 (all works in progress), including the one this is happening on, however other 256x256 maps are unaffected. 

The only change I've done between the map working and the map giving this error was adding more tiles (trees), see attached. Basically that area of the map was blank, after adding that section the map throws me the error.
![broken map](https://user-images.githubusercontent.com/41254118/42731862-44cf448a-8855-11e8-9db7-7cd365bfb7e7.PNG)

**Comment by AFKLord** [comment]
I can confirm that after clearing all the tree tiles from that area, the map works fine again. Any way the plugin can be fixed to not have a heart attack when I tile an area as such?

**Comment by felixjones** [comment]
The way the collision tree is traversed uses recursion, so the more collision geometry the deeper the recursion goes; eventually this will hit the Javascript call stack limit and crash in this way.

I'll investigate now and see if it can be solved.

EDIT: Okay the issue seems to be JSON.stringify cannot handle large & complex JSON files, so that's a bit annoying (it's a Javascript issue...). It isn't related to the recursive traversion, oddly. This should be fixable with a replacement JSON loader.

**Comment by felixjones** [comment]
Okay I've replaced JSON.stringify with the custom JSON.prune function, which fixes this issue.

Do keep in mind that large, complex maps will have performance issues. This error is a symptom of the map getting too complex.
